### ISSUE TITLE
Does this repo further fragment abb support?

### ISSUE THREAD

**Issue by davetcoleman** [ros-industrial/abb_experimental#93]
Wouldn't this code be better kept in the main https://github.com/ros-industrial/abb/ repo as the latest branch, and keep older branches for backwards compatibility? Otherwise you really confuse developers which to use / contribute to / focus on. This is messy. When does "experimental" no longer become experimental?

**Comment by gavanderhoorn** [comment]
Please refer to #46 (perhaps specifically https://github.com/ros-industrial/abb_experimental/issues/46#issuecomment-304306857). There is a specific reason for why we have `_experimental` repositories in ROS-Industrial.

This repository is not something where old branches / pkgs are stored or bw compatibility is maintained. Experimental pkgs are experimental, that's why they are hosted here.

**Comment by gavanderhoorn** [comment]
As this is not an actual bug or issue with the pkgs in this repository, I'll close it, but feel free to keep commenting.
